import Head from "next/head";
import Image from "next/image";
import { pokeApi } from "../api";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="">Pokedex</main>

      <footer className=""></footer>
    </div>
  );
}

export const getStaticProps = async () => {
  try {
    const res = await pokeApi.get("/pokemon?limit=151");
    return {
      props: { data: res.data.results },
    };
  } catch (error) {
    console.log(error);
  }
};
